# Generated by Django 3.1.1 on 2020-09-29 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200929_0615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='img_url',
            new_name='image',
        ),
    ]
